AllCops:
  Exclude:
    - vendor/**/*
    - ruby/**/*
    - files/**/*

Next:
  Enabled: false
AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
RegexpLiteral:
  Enabled: false
