#
# Cookbook Name:: fen-build-farm
# Recipe:: plugins
#
# Copyright 2015, Family Education Network
#
# All rights reserved - Do Not Redistribute
#

credentials = search('jenkins').first
node.run_state[:jenkins_private_key] = credentials['private_key']
node.run_state[:jenkins_username] = 'karl.debisschop@fen.com'

jenkins_plugin 'aws-java-sdk'
jenkins_plugin 'android-emulator'
jenkins_plugin 'android-lint'
jenkins_plugin 'build-keeper-plugin'
jenkins_plugin 'build-pipeline-plugin'
jenkins_plugin 'checkstyle'
jenkins_plugin 'cloverphp'
jenkins_plugin 'compact-columns'
jenkins_plugin 'config-file-provider'
jenkins_plugin 'copyartifact'
jenkins_plugin 'delivery-pipeline-plugin'
jenkins_plugin 'disk-usage'
jenkins_plugin 'downstream-buildview'
jenkins_plugin 'dry'
jenkins_plugin 'email-ext'
jenkins_plugin 'envinject'
jenkins_plugin 'environment-script'
jenkins_plugin 'job-exporter'
jenkins_plugin 'external-monitor-job'
jenkins_plugin 'git-client'
jenkins_plugin 'git'
jenkins_plugin 'google-login'
jenkins_plugin 'google-play-android-publisher'
jenkins_plugin 'gradle'
jenkins_plugin 'hockeyapp'
jenkins_plugin 'hsts-filter-plugin'
jenkins_plugin 'htmlpublisher'
jenkins_plugin 'flashlog-plugin'
jenkins_plugin 'jdepend'
jenkins_plugin 'join'
jenkins_plugin 'jquery'
jenkins_plugin 'jquery-ui'
jenkins_plugin 'mapdb-api'
jenkins_plugin 'mask-passwords'
jenkins_plugin 'multiple-scms'
jenkins_plugin 'nested-view'
jenkins_plugin 'nodelabelparameter'
jenkins_plugin 'parameterized-trigger'
jenkins_plugin 'plot'
jenkins_plugin 'pmd'
jenkins_plugin 'port-allocator'
jenkins_plugin 'project-description-setter'
jenkins_plugin 'publish-over-ssh'
jenkins_plugin 'run-condition'
jenkins_plugin 's3'
jenkins_plugin 'scm-api'
jenkins_plugin 'slack'
jenkins_plugin 'ssh-agent'
jenkins_plugin 'analysis-core'
jenkins_plugin 'svn-tag'
jenkins_plugin 'token-macro'
jenkins_plugin 'build-user-vars-plugin'
jenkins_plugin 'workflow-aggregator'
jenkins_plugin 'ws-cleanup'
jenkins_plugin 'xcode-plugin'
jenkins_plugin 'xunit'
