---
driver:
   name: vagrant

driver_config:
  customize:
    memory: 4096
  network:
    - - forwarded_port
      - guest: 9000
        host: 9000
        auto_correct: true
    - - forwarded_port
      - guest: 12900
        host: 12900
        auto_correct: true
    - - forwarded_port
      - guest: 12201
        host: 12201
        auto_correct: true 

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.4.1'
  data_path: test

platforms:
- name: centos-6.7
  attributes:
    mongodb:
      reload_action: "reload"
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: debian-7.8
  run_list:
  - recipe[apt]

suites:
  - name: default
    attributes:
      machine_fqdn: graylog.local
      machine_fqdn_as_hostname: true
      java:
        set_default: true
        jdk_version: '8'
        install_flavor: 'oracle'
        oracle:
          accept_oracle_download_terms: true
      graylog2:
        password_secret: "2jueVqZpwLLjaWxV"
        root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        web:
          secret: "2jueVqZpwLLjaWxV"
        restart: "delayed"
        rest:
          admin_access_token: "F3DenL9HXW12KECdLmrfQ8HNGW4zwbwlJSyo7PxlsgHvgeay5F3tQhnoH6T2G7X3iiy2bcYPClsjCWi1PIY48sCSSyoW4H64"
        inputs:
          - '{"title": "syslog", "type":"org.graylog2.inputs.syslog.udp.SyslogUDPInput", "global": true, "configuration": { "port": 1514, "allow_override_date": true, "bind_address": "0.0.0.0", "store_full_message": true, "recv_buffer_size": 1048576 }}'
        streams: 
          - '{"title":"Demo Stream","description":"Show all GETs", "rules": [{"field":"message","value":"GET.*","type":2,"inverted":false}, {"field":"message","value":".*/login.*","type":2,"inverted":false}], "alarm_callbacks": [{"configuration": { "sender": "graylog@example.org", "body": "Demo Alert", "subject": "Graylog alert for stream: ${stream.title}" }, "type": "org.graylog2.alarmcallbacks.EmailAlarmCallback"}], "alert_conditions": [{"type":"message_count", "parameters":{"grace":10,"time":5,"threshold_type":"more","backlog":1,"threshold":3}}]}'
        dashboards:
          - '{"title": "Demo SSH Dashboard", "description": "SSH related widgets", "widgets": [ { "description": "SSH messages", "config": { "interval": "minute", "query": "*", "range_type": "relative", "range": "0" },  "position": {"row": 1,"col": 2 }, "type": "search_result_chart" }, { "description": "No. SSH logins", "config": { "query": "message:sshd AND message:opened", "range_type": "relative", "range": "0" }, "type": "search_result_count" } ] }'
      elasticsearch:
        version: "1.7.1"
        cluster:
          name: "graylog2"
    run_list:
      - recipe[fqdn]
      - recipe[mongodb]
      - recipe[java]
      - recipe[elasticsearch]
      - recipe[graylog2]
      - recipe[graylog2::server]
      - recipe[graylog2::web]
      - recipe[graylog2::radio]
      - recipe[graylog2::collector]
      - recipe[graylog2::authbind]
